In [3]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import AgglomerativeClustering
from scipy.cluster.hierarchy import linkage, dendrogram, fcluster

In [24]:
# example 1
line1_features = np.array([2, 4, 6, 8, 10])
line2_features = np.array([7, 9, 8, 29, 11])
# ...

print(line1_features)
print(line2_features)
print()

pca1 = [1.2, -3.4, 5.5, 0.8, 1.1]  # i made up random numbers

# print(line1_features * pca1)
# print(np.sum(line1_features * pca1))
line1_pca1 = np.sum(line1_features * pca1)
print([line1_pca1])

# print(line2_features * pca1)
# print(np.sum(line2_features * pca1))
line2_pca1 = np.sum(line2_features * pca1)
print([line2_pca1])

# calca variance .... usually we would like 70%+
print('not good varaice , add another pca...')
print()

pca2 = [0.2, -1.4, 3.77, 0.5, -1.9]  # i made up random numbers

# print(line1_features * pca2)
# np.sum(line1_features * pca2)
line1_pca2 = np.sum(line1_features * pca2)

# print(line2_features * pca2)
# print(np.sum(line2_features * pca2))
line2_pca2 = np.sum(line2_features * pca2)

print([line1_pca1, line1_pca2])
print([line2_pca1, line2_pca2])

# line1_features = np.array([2, 4, 6, 8, 10])
# line2_features = np.array([7, 9, 8, 29, 11])

[ 2  4  6  8 10]
[ 7  9  8 29 11]

[39.2]
[57.10000000000001]
not good varaice , add another pca...

[39.2, 2.4200000000000017]
[57.10000000000001, 12.560000000000002]


In [36]:
# example 2
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# 1. Load dataset
df = pd.read_csv("Churn_Modelling.csv")

# 2. Keep only numeric columns (ignore text like Geography, Gender, etc.)
df_numeric = df.select_dtypes(include=["float64", "int64"])

# 3. Standardize the features
scaler = StandardScaler()
scaled_data = scaler.fit_transform(df_numeric)

pca = PCA()
pca_result = pca.fit_transform(scaled_data)

print(pca_result.shape)
pca.explained_variance_ratio_ * 100
np.cumsum(pca.explained_variance_ratio_ * 100)

(10000, 11)


array([ 12.93547593,  23.75254327,  33.73313264,  43.10402318,
        52.2301439 ,  61.30109839,  70.26395332,  79.18924743,
        87.98945142,  94.41205632, 100.        ])